module.exports = {
  app: 'src/',
  dist: 'docs/',
  test: 'test/',
  bower: 'src/bower_components/',
  npm: 'src/node_modules/',
  node_modules: 'node_modules/',
  tmp: '.tmp/',
  revManifest: '.tmp/rev-manifest.json',
  port: 9090,
  liveReloadPort: 35729,
  uri: 'http://localhost:',
  constantTemplate: '\'use strict\'\n\n// DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n' +
		'angular\n' +
		'	.module(\'<%- moduleName %>\')\n' +
		'<% constants.forEach(function(constant) { %>		.constant(\'<%- constant.name %>\', <%= constant.value %>)\n<% }) %>;\n'
};
